FROM node:alpine
WORKDIR /app
EXPOSE 3000
COPY package*.json ./
RUN npm install
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
#Enviroments values
ARG REACT_APP_HOST_SERVER
ENV REACT_APP_HOST_SERVER=$REACT_APP_HOST_SERVER
COPY . ./
CMD ["npm", "start"]